# reports/html_renderer.py

from jinja2 import Template

HTML_TEMPLATE = r"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Hexora Enterprise SAST Report</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<style>
body { background: #f4f6f9; padding: 32px; font-family: system-ui; }
.card { border-radius: 16px; box-shadow: 0 6px 20px rgba(0,0,0,.09); }
.codebox { background:#1e1e1e; color:#fff; padding:12px; border-radius:6px; font-family:monospace; white-space:pre-wrap; }
.metric-box { background:white; border-left:6px solid #0b3d91; padding:14px; border-radius:12px; margin-bottom:12px; }
</style>

</head>
<body>

<div class="container">

<div class="card p-4 mb-4">
    <h2 class="text-primary fw-bold">Hexora Enterprise SAST Scan Report</h2>
    <p class="text-muted">Generated: {{meta.timestamp}}</p>
    <p><b>Total Files:</b> {{meta.total_files}} &nbsp; | &nbsp; <b>Total Findings:</b> {{meta.total_findings}}</p>
</div>

<div class="row">

    <div class="col-md-4">
        <canvas id="severityPie"></canvas>
    </div>

    <div class="col-md-8">
        {% for sev, count in sev_counts.items() %}
        <div class="metric-box">
            <b class="text-capitalize">{{sev}}</b> : {{count}}
        </div>
        {% endfor %}
        <div class="metric-box">
            <b>Project Risk Score:</b> {{risk_score}} / 100
        </div>
    </div>

</div>

<div class="card p-4 mt-4">
<h3 class="fw-bold">Findings Details</h3>

{% for f in findings %}
<div class="p-3 mb-4 border-start border-4" style="border-color:#0b3d91;">
    <h4>{{f.rule}} <span class="badge bg-danger">{{f.severity}}</span></h4>

    <p><b>Category:</b> {{f.category}}</p>
    <p><b>File:</b> {{f.file}}</p>
    <p><b>Line:</b> {{f.line_no}}</p>

    <p><b>CWE:</b> {{f.cwe}} | 
       <b>OWASP:</b> {{f.owasp}} | 
       <b>CVSS:</b> {{f.cvss}}</p>

    <p><b>Description:</b> {{f.description}}</p>
    <p><b>Remediation:</b> {{f.remediation}}</p>

    <div class="codebox">{{f.line}}</div>
</div>
{% endfor %}

</div>

<script>
new Chart(document.getElementById('severityPie'), {
    type: 'pie',
    data: {
        labels: ['Critical', 'High', 'Medium', 'Low'],
        datasets: [{
            data: [
                {{sev_counts.critical}},
                {{sev_counts.high}},
                {{sev_counts.medium}},
                {{sev_counts.low}}
            ],
            backgroundColor:['#d62828','#f77f00','#fcbf49','#1d4ed8']
        }]
    }
});
</script>

<footer class="text-center mt-5 text-muted">
    Generated by <b>Hexora SAST Engine v2.0</b>
</footer>

</body>
</html>
"""

class HTMLRenderer:
    @staticmethod
    def render(findings, meta):

        # severity counters
        sev_counts = {"critical":0,"high":0,"medium":0,"low":0}
        for f in findings:
            sev_counts[f["severity"]] += 1

        weighted = sev_counts["critical"]*10 + sev_counts["high"]*7 + sev_counts["medium"]*4 + sev_counts["low"]
        total = max(1, sum(sev_counts.values()))
        risk_score = int((weighted / (total * 10)) * 100)

        tpl = Template(HTML_TEMPLATE)
        return tpl.render(
            findings=findings,
            meta=meta,
            sev_counts=sev_counts,
            risk_score=risk_score
        )